<?php
require '../config/config.php';
require '../includes/fpdf.php';

class PDF extends FPDF {
    // Header with logo and title
    function Header() {
        // Background color for the top section
        $this->SetFillColor(10, 45, 100);
        $this->Rect(0, 0, 215, 40, 'F'); // ✅ Extended width from 210 to 215 to cover right edge perfectly

        // Logo
        $this->Image('../public/asset/images/mortarboard.png', 95, 8, 20);

        // University name
        $this->SetFont('Arial', 'B', 16);
        $this->SetTextColor(255, 255, 255);
        $this->Ln(25);
        $this->Cell(0, 5, 'UNIVERSITY OF TECHNOLOGY', 0, 1, 'C');
        $this->SetFont('Arial', '', 12);
        $this->Cell(0, 7, 'REPORT CARD', 0, 1, 'C');
        $this->Ln(8);
    }


    // Footer with date/time and text
    function Footer()
    {
        $this->SetY(-20);
        $this->SetFont('Arial', 'I', 9);
        $this->SetTextColor(128, 128, 128);

        // --- Date and time ---
        date_default_timezone_set('Africa/Mogadishu');
        $this->Cell(0, 10, 'Generated on: ' . date('d M Y, h:i A'), 0, 1, 'L');

        // --- Footer text ---
        $this->Cell(0, 10, 'Generated by Student Management System', 0, 0, 'C');
    }

    // Title section
    function SectionTitle($title) {
        $this->SetFont('Arial', 'B', 12);
        $this->SetTextColor(255, 255, 255);
        $this->SetFillColor(10, 45, 100);
        $this->Cell(0, 10, strtoupper($title), 0, 1, 'C', true);
        $this->Ln(3);
    }

    // Student info table
    function StudentInfo($student) {
        $this->SetFont('Arial', '', 11);
        $this->SetTextColor(0);
        $this->SetFillColor(240, 245, 255);

        // Two-column table for details
        $this->Cell(95, 8, 'Student Name: ' . strtoupper($student['name']), 1, 0, 'L', true);
        $this->Cell(95, 8, 'Student ID: ' . $student['id'], 1, 1, 'L', true);
        $this->Cell(95, 8, 'Email: ' . $student['email'], 1, 0, 'L', true);
        $this->Cell(95, 8, 'Phone: ' . $student['phone'], 1, 1, 'L', true);
        $this->Ln(10);
    }

    // Student exams section placeholder
    function ExamsSection() {
        $this->SectionTitle('STUDENT EXAMS');
        $this->SetFont('Arial', 'I', 11);
        $this->SetTextColor(100);
        $this->Cell(0, 8, 'Exam details will appear here.', 0, 1, 'C');
    }
}

// Fetch student info
if (isset($_GET['id'])) {
    $id = intval($_GET['id']);
    $result = $conn->query("SELECT * FROM student_info WHERE id = $id");
    $student = $result->fetch_assoc();

    $pdf = new PDF();
    $pdf->AddPage();

    // Student information section
    $pdf->SectionTitle('STUDENT INFORMATION');
    $pdf->StudentInfo($student);

    // Exams section placeholder
    $pdf->ExamsSection();

    // Output PDF
    $filename = 'Student_Report_' . strtoupper($student['name']) . '.pdf';
    $pdf->Output('D', 'Student_Report_' . $student['name'] . '.pdf');
} else {
    echo "Student ID not provided.";
}
?>
